### ISSUE TITLE
Replace cURL with HTTP API

### ISSUE THREAD

**Issue by koenHuybrechts** [AppSaloon/woocommerce-payconiq#3]
(feedback of the plugin review)

WordPress comes with an extensive HTTP API that should be used instead of creating your own curl calls. It’s both faster and more extensive. It’ll fall back to curl if it has to, but it’ll use a lot of WordPress’ native functionality first.

https://developer.wordpress.org/plugins/http-api/

**Comment by aytackokus** [comment]
Fixed by 04560b4
